sudo: false
language: go
go:
  - 1.5.4
  - 1.6.3
  - 1.7
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -v
notifications:
  email: false
